services:
  fpm:
    build:
      dockerfile: fpm_dockerfile
    restart: always
    ports:
        - ":9000"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

    volumes:
        - ./wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql

  nginx:
    build:
      dockerfile: Dockerfile
    environment:
      - NGINX_HOST=ai4fin.tech
      - NGINX_PORT=80
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./sites-enabled/:/etc/nginx/sites-enabled
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./wordpress:/var/www/html
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s --with-http_sub_module reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - fpm

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  turn:
    image: coturn/coturn
    restart: always
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "3479:3479"
      - "3479:3479/udp"
    volumes:
      - ./coturn/turnserver.conf:/etc/turnserver.conf:ro
